-- MySQL Script generated by MySQL Workbench
-- Thu Feb  6 20:23:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tbt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tbt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tbt` DEFAULT CHARACTER SET utf8 ;
USE `tbt` ;

-- -----------------------------------------------------
-- Table `tbt`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt`.`news` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `media` VARCHAR(45) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL,
  `score` VARCHAR(45) NULL DEFAULT NULL,
  `magnitude` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `media` (`media` ASC) VISIBLE,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt`.`article` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `article` VARCHAR(3000) NULL DEFAULT NULL,
  `news_url` VARCHAR(255) NOT NULL,
  `tokenize` VARCHAR(3000) NULL,
  PRIMARY KEY (`id`, `news_url`),
  INDEX `fk_article_news1_idx` (`news_url` ASC) VISIBLE,
  CONSTRAINT `fk_article_news1`
    FOREIGN KEY (`news_url`)
    REFERENCES `tbt`.`news` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt`.`keyword` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(100) NULL DEFAULT NULL,
  `news_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_keyword_news1_idx` (`news_id` ASC) VISIBLE,
  CONSTRAINT `fk_keyword_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `tbt`.`news` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt`.`reporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt`.`reporter` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt`.`reporter_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt`.`reporter_has_news` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `reporter_id` BIGINT(20) NOT NULL,
  `news_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `reporter_id`, `news_id`),
  INDEX `fk_reporter_has_news_news1_idx` (`news_id` ASC) VISIBLE,
  INDEX `fk_reporter_has_news_reporter1_idx` (`reporter_id` ASC) VISIBLE,
  CONSTRAINT `fk_reporter_has_news_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `tbt`.`news` (`id`),
  CONSTRAINT `fk_reporter_has_news_reporter1`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `tbt`.`reporter` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
