-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 10:28:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tbt_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tbt_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tbt_test` DEFAULT CHARACTER SET utf8 ;
USE `tbt_test` ;

-- -----------------------------------------------------
-- Table `tbt_test`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt_test`.`news` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `media` VARCHAR(45) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `score` VARCHAR(45) NULL DEFAULT NULL,
  `magnitude` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  INDEX `media` (`media` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt_test`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt_test`.`article` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `article` VARCHAR(3000) NULL DEFAULT NULL,
  `news_url` VARCHAR(255) NOT NULL,
  `tokenize` VARCHAR(3000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `news_url`),
  INDEX `fk_article_news1_idx` (`news_url` ASC) VISIBLE,
  CONSTRAINT `fk_article_news1`
    FOREIGN KEY (`news_url`)
    REFERENCES `tbt_test`.`news` (`url`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt_test`.`keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt_test`.`keyword` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `keyword` VARCHAR(100) NULL DEFAULT NULL,
  `news_id` BIGINT(20) NOT NULL,
  `add_in_dict` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_keyword_news1_idx` (`news_id` ASC) VISIBLE,
  CONSTRAINT `fk_keyword_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `tbt_test`.`news` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt_test`.`reporter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt_test`.`reporter` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `media` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tbt_test`.`reporter_has_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tbt_test`.`reporter_has_news` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `reporter_id` BIGINT(20) NOT NULL,
  `news_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`, `reporter_id`, `news_id`),
  INDEX `fk_reporter_has_news_news1_idx` (`news_id` ASC) VISIBLE,
  INDEX `fk_reporter_has_news_reporter1_idx` (`reporter_id` ASC) VISIBLE,
  CONSTRAINT `fk_reporter_has_news_news1`
    FOREIGN KEY (`news_id`)
    REFERENCES `tbt_test`.`news` (`id`),
  CONSTRAINT `fk_reporter_has_news_reporter1`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `tbt_test`.`reporter` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

USE `tbt_test` ;

-- -----------------------------------------------------
-- procedure doiterate
-- -----------------------------------------------------

DELIMITER $$
USE `tbt_test`$$
CREATE DEFINER=`test`@`localhost` PROCEDURE `doiterate`()
BEGIN
  DECLARE i INT unsigned DEFAULT 19917;
  WHILE i <= 21132 DO
    UPDATE `keyword` SET `add_in_dict`='no' WHERE `id`=i;
    SET i = i + 1;
  END WHILE;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
